version: '3'
services:
  mysql:
    image: mysql:8.0.34 # 使用的镜像
    container_name: mysql # 启动的实例名称
    privileged: true # 增加权限
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root 用户密码
    ports:
      - "13306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络
  redis:
    image: redis:7.2.2
    container_name: redis
    ports:
      - "16379:6379"
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化
    command: redis-server --requirepass 123456 # redis 密码
  rabbitmq:
    image: rabbitmq:3.12.6-management # 支持管理面板的消息队列
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Dashboard 端口
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化
    networks:
      - mynetwork
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
      - NACOS_AUTH_ENABLE=true # 是否开启权限系统
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=18000 # token 失效时间，默认 18000
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789 # token
      - NACOS_AUTH_CACHE_ENABLE=true # 权限缓存开关, 开启后权限缓存的更新默认有15秒的延迟
      - nacos.core.auth.system.type=nacos # 身份验证账号
      - nacos.core.auth.server.identity.key=nacosKey # 客户端身份密钥
      - nacos.core.auth.server.identity.value=123456 # 客户端身份密钥的值
networks:
  mynetwork:
