server:
  port: 8101

spring:
  application:
    name: haifoj-gateway
    # 默认 dev 环境
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: haifoj-judge-service
          uri: lb://haifoj-judge-service
          predicates:
            - Path=/api/judge/**
        - id: haifoj-question-service
          uri: lb://haifoj-question-service
          predicates:
            - Path=/api/question/**
        - id: haifoj-user-service
          uri: lb://haifoj-user-service
          predicates:
            - Path=/api/user/**

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2